const types = {
  'DIALOGS:SET_ITEMS': 'DIALOGS:SET_ITEMS',
  'DIALOGS:SET_CURRENT_DIALOG_ID': 'DIALOGS:SET_CURRENT_DIALOG_ID',
  'MESSAGES:SET_ITEMS': 'MESSAGES:SET_ITEMS',
  'MESSAGES:SET_IS_LOADING': 'MESSAGES:SET_IS_LOADING',
  'USER:SET_DATA': 'USER:SET_DATA',
  'USER:SET_IS_AUTH': 'USER:SET_IS_AUTH',
};

export default types;
